name: Deploy blog 
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.19.1
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}

